name = "uaintel"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "uaintel-community"
database_id = "816fe6cd-28c0-4777-8881-4847b6ecd0a2"

[[kv_namespaces]]
binding = "CACHE"
id = "ba5b41d6772d461988a960098b511234"

[triggers]
crons = ["0 0 * * SUN"]  # Weekly Sunday midnight

[vars]
RATE_LIMIT_ANALYZE = "30"
RATE_LIMIT_REPORT = "10"
